### ISSUE TITLE
Agendar scan de segurança com cronjob do github actions

### ISSUE THREAD

**Issue by gomex** [DadosAbertosDeFeira/iac-docker-tika#10]
Em caso de problema, deve ser enviado uma mensagem para o canal do discord e criar uma issue no github.

Podemos discutir depois o canal.

**Comment by mmmarceleza** [comment]
Comecei a trabalhar na solução dessa issue.

**Comment by mmmarceleza** [comment]
@gomex , tem uma pendência nessa issue ainda. O push da imagem não rolou com a criação da release. Vou tentar resolver essa parada.
