### ISSUE TITLE
Corrigir versão usada para fazer upload da imagem no docker hub

### ISSUE THREAD

**Issue by gomex** [DadosAbertosDeFeira/iac-docker-tika#14]
Hoje a versão da imagem que é feito o upload é a versão binário do tika usado nessa imagem, mas essa imagem pode sofrer várias modificações e a versão do tika continuará a mesma. 

Precisamos pegar o numero da versão daqui do github, o mesmo da release e não o numero estático que passamos da versão do tika, pois nesse ultimo caso sobrecreveremos a image caso a versão do tika não mude entre uma mudança e outra.

https://github.com/DadosAbertosDeFeira/iac-docker-tika/blob/256977a7dbf984973714a0eca15480e1e2a0bd51/.github/workflows/main.yml#L147

**Comment by mmmarceleza** [comment]
@gomex, como o PR foi mergeado, essa issue pode ser fechada.

**Comment by gomex** [comment]
Problema ja resolvido
