### ISSUE TITLE
Reiniciar caso serviço seja interrompido

### ISSUE THREAD

**Issue by anapaulagomes** [DadosAbertosDeFeira/iac-docker-tika#18]
Às vezes temos casos onde o Tika precisa processar um arquivo muito grande e isso acaba gerando uma sobrecarga na memória. Então o container é interrompido e não retorna. Precisamos que ele seja capaz de reiniciar sozinho caso seja parado por algum motivo.

**Comment by gomex** [comment]
O pipeline ainda está quebrando: https://github.com/DadosAbertosDeFeira/iac/runs/5626388949?check_suite_focus=true

Precisamos corrigir o deploy.

**Comment by gomex** [comment]
Corrigido: https://github.com/DadosAbertosDeFeira/iac/runs/5636605318?check_suite_focus=true

```
docker inspect tika-server | grep "RestartPolicy" -A 2
            "RestartPolicy": {
                "Name": "unless-stopped"
```
